// src/utils/templateGenerator.js
import { v4 as uuidv4 } from "uuid";

const generateTemplate = (type, options = {}) => {
  const baseUUID = () => uuidv4();
  const {
    name = "Example",
    description = "Generated by Minecraft JSON Generator",
    version = [1, 0, 0]
  } = options;

  switch (type) {
    case "manifest_bp":
      return {
        format_version: 2,
        header: {
          name,
          description,
          uuid: baseUUID(),
          version
        },
        modules: [
          {
            type: "data",
            uuid: baseUUID(),
            version
          }
        ]
      };

    case "manifest_rp":
      return {
        format_version: 2,
        header: {
          name,
          description,
          uuid: baseUUID(),
          version
        },
        modules: [
          {
            type: "resources",
            uuid: baseUUID(),
            version
          }
        ]
      };

    // definitions
    case "block":
      return {
        format_version: "1.16.100",
        "minecraft:block": {
          description: {
            identifier: "example:block"
          },
          components: {
            "minecraft:destroy_time": 1.0
          }
        }
      };

    case "item":
      return {
        format_version: "1.16.100",
        "minecraft:item": {
          description: {
            identifier: "example:item",
            category: "Misc"
          },
          components: {
            "minecraft:icon": "textures/items/example"
          }
        }
      };

    case "sound":
      return {
        format_version: "1.16.0",
        sound_definitions: {
          "example:sound": {
            category: "ambient",
            sounds: [
              {
                name: "sounds/example_sound",
                volume: 1.0,
                pitch: 1.0
              }
            ]
          }
        }
      };

    default:
      return {};
  }
};

export default generateTemplate;